substitutions:
  first_page_id: first_page
  page_transition_time: 150ms # How long to animate the transition between pages.

globals:
  - id: current_page
    type: int
    restore_value: no
    initial_value: "0"
  - id: page_controls_hidden
    type: bool
    initial_value: "false"
    restore_value: no

script:
  - id: hide_page_control_elements
    then:
      - lvgl.widget.hide: top_tap_area
      - lvgl.widget.hide: bottom_tap_area
      - lvgl.widget.hide: left_tap_area
      - lvgl.widget.hide: right_tap_area
      - lvgl.widget.hide: bottom_pager
      - globals.set:
          id: page_controls_hidden
          value: 'true'


  - id: show_page_control_elements
    then:
      - lvgl.widget.show: top_tap_area
      - lvgl.widget.show: bottom_tap_area
      - lvgl.widget.show: left_tap_area
      - lvgl.widget.show: right_tap_area
      - lvgl.widget.show: bottom_pager
      - globals.set:
          id: page_controls_hidden
          value: 'false'
  
  - id: go_to_first_page
    then:
      - globals.set:
          id: current_page
          value: '0'
      - lvgl.page.show:
          id: ${first_page_id}
          animation: MOVE_LEFT
      - script.execute: update_pager_dots
 
  - id: next_page
    then:
      - globals.set:
          id: current_page
          value: !lambda |-
            int next_page = id(current_page) + 1;
            return (next_page >= ${total_pages}) ? 0 : next_page;  // Loop back to 0 if exceeding the total pages
      - lvgl.page.next:
          animation: MOVE_LEFT
          time: ${page_transition_time}
      - script.execute: update_pager_dots

  - id: previous_page
    then:
      - globals.set:
          id: current_page
          value: !lambda |-
            int prev_page = id(current_page) - 1;
            return (prev_page < 0) ? ${total_pages} - 1 : prev_page;  // Loop back to max page if going below 0
      - lvgl.page.previous:
          animation: MOVE_RIGHT
          time: ${page_transition_time}
      - script.execute: update_pager_dots
