substitutions:
  first_page_id: first_page

esphome:
  on_boot:
    - priority: 800.0
      then:
        - script.execute: create_pager_dots

globals:
  - id: current_page
    type: int
    restore_value: no
    initial_value: "0"
  - id: pager_dots
    type: lv_obj_t*[${total_pages}]
    restore_value: no
  - id: page_controls_hidden
    type: bool
    initial_value: "false"
    restore_value: no

script:
  - id: hide_page_control_elements
    then:
      - lvgl.widget.hide: top_tap_area
      - lvgl.widget.hide: bottom_tap_area
      - lvgl.widget.hide: left_tap_area
      - lvgl.widget.hide: right_tap_area
      - lvgl.widget.hide: bottom_pager
      - globals.set:
          id: page_controls_hidden
          value: 'true'


  - id: show_page_control_elements
    then:
      - lvgl.widget.show: top_tap_area
      - lvgl.widget.show: bottom_tap_area
      - lvgl.widget.show: left_tap_area
      - lvgl.widget.show: right_tap_area
      - lvgl.widget.show: bottom_pager
      - globals.set:
          id: page_controls_hidden
          value: 'false'

  - id: create_pager_dots
    then:
      - lambda: |-
          for (int i = 0; i < ${total_pages}; i++) {
            auto dot = lv_obj_create(id(bottom_pager));  // Create each dot object
            lv_obj_set_size(dot, 8, 8);  // Set width and height of the dot (8x8)
            lv_obj_set_style_radius(dot, 4, LV_PART_MAIN);  // Set radius to make it circular
            lv_obj_set_style_bg_color(dot, (i == 0) ? lv_color_hex(0xffffff) : lv_color_hex(0x626262), LV_PART_MAIN);  // Set color based on active/inactive
            lv_obj_set_style_bg_opa(dot, LV_OPA_COVER, LV_PART_MAIN);  // Ensure the background is fully opaque
            lv_obj_set_style_border_width(dot, 0, LV_PART_MAIN);  // Disable borders
            lv_obj_set_style_border_color(dot, lv_color_hex(0x000000), LV_PART_MAIN);  // Set border color to black (doesn't matter since width is 0)
            id(pager_dots)[i] = dot;  // Store the dot reference
          }

  - id: update_pager_dots
    then:
      - lambda: |-
          for (int i = 0; i < ${total_pages}; i++) {
            lv_obj_t* dot = id(pager_dots)[i];
            lv_obj_set_style_bg_color(dot, (i == id(current_page)) ? lv_color_hex(0xffffff) : lv_color_hex(0x626262), LV_PART_MAIN);  // Active color is white, inactive is gray
          }
  
  - id: go_to_first_page
    then:
      - globals.set:
          id: current_page
          value: '0'
      - lvgl.page.show:
          id: ${first_page_id}
          animation: MOVE_LEFT
      - script.execute: update_pager_dots
 
  - id: next_page
    then:
      - globals.set:
          id: current_page
          value: !lambda |-
            int next_page = id(current_page) + 1;
            return (next_page >= ${total_pages}) ? 0 : next_page;  // Loop back to 0 if exceeding the total pages
      - lvgl.page.next:
          animation: MOVE_LEFT
          time: ${page_transition_time}
      - script.execute: update_pager_dots

  - id: previous_page
    then:
      - globals.set:
          id: current_page
          value: !lambda |-
            int prev_page = id(current_page) - 1;
            return (prev_page < 0) ? ${total_pages} - 1 : prev_page;  // Loop back to max page if going below 0
      - lvgl.page.previous:
          animation: MOVE_RIGHT
          time: ${page_transition_time}
      - script.execute: update_pager_dots
