substitutions:
  device_name: "sensecap-indicator"
  device_friendly_name: "SenseCAP Dashboard"

packages:
  app: !include HomeDicator/app.yaml
  hardware:  !include HomeDicator/hardware/seeed_sensecap_indicator.yaml
  theme: !include HomeDicator/themes/480x480/theme.yaml
