substitutions:
  screen_width: 240
  screen_height: 240

  size14: 7
  size18: 9
  size20: 10
  size24: 12
  size25: 13
  size30: 15
  size32: 16
  size35: 18
  size50: 25

packages:
  lvgl: !include ../common/lvgl.yaml
  fonts: !include ../common/fonts.yaml

lvgl:
  style_definitions:
    - id: full_width
      x: 0
      width: ${screen_width}
    - id: full_height
      y: 0
      height: ${screen_height}
    - id: bottom_pager_y
      y: 225
    - id: bottom_tap_area_y
      y: 217
    - id: bottom_tap_area_widget_size
      height: 22
      width: 117
    - id: top_tap_area_y
      y: 0
      height: 35
    - id: leftright_tap_area
      y: 35
      width: 10
      height: 175
    - id: right_tap_area_x
      x: 230
    - id: content_container
      x: 0
      y: 45
      width: ${screen_width}
      height: 171
      pad_all: 0
      pad_left: 9
      bg_opa: TRANSP
    - id: left_central_tap_area 
      x: 10
      y: 10
      width: !lambda return ${screen_width}/2 - 20;
      height: !lambda return ${screen_height} - 2*20;
    - id: right_central_tap_area 
      x: !lambda return ${screen_width}/2;
      y: 10
      width: !lambda return ${screen_width}/2 - 20;
      height: !lambda return ${screen_height} - 2*20;
    - id: page_title_y
      y: 25
    
    # Settings page
    - id: back_button
      x: 3
      height: 20
    - id: settings_item
      width: 221
      radius: 7
      height: 40
    - id: settings_display_brightness_height
      height: 75
    - id: settings_display_brightness_slider
      height: 12
    - id: settings_dropdown
      height: 20
      width: 55
    - id: settings_item_internal_width
      width: 220

    # Floorplan 
    - id: floorplan_pill
      bg_color: 0x000000
      bg_opa: 20%
      radius: 4
      pad_all: 1
      pad_left: 2
      pad_right: 2
      border_width: 0
      width: SIZE_CONTENT
      height: SIZE_CONTENT

    - id: floorplan_pill_large
      bg_color: 0x000000
      bg_opa: 20%
      radius: 5
      pad_all: 2
      pad_left: 3
      pad_right: 3
      border_width: 0
      width: SIZE_CONTENT
      height: SIZE_CONTENT

    - id: floorplan_icon
      text_color: 0xffffff
      text_font: icons18

    - id: floorplan_icon_large
      text_color: 0xffffff
      text_font: icons35

    - id: floorplan_value
      text_color: 0xffffff
      text_font: libreFranklin14

    - id: floorplan_value_large
      text_color: 0xffffff
      text_font: libreFranklin18
 
    # Info tiles
    - id: info_or_button_tile
      width: 108
      height: 82
      radius: 7
      bg_color: 0x272727
      bg_opa: COVER
      pad_all: 0
    - id: info_or_button_tile_icon_container
      pad_all: 0
      height: 26
      width: 50
      radius: 12
    - id: info_or_button_tile_small
      width: 70
      height: 53
      radius: 7
      bg_color: 0x272727
      bg_opa: COVER
      pad_all: 0
    - id: info_or_button_tile_wide
      width: 221
      height: 82
      radius: 7
      bg_color: 0x272727
      bg_opa: COVER
      pad_all: 0
    - id: info_or_button_tile_icon
      pad_all: 0
      text_color: 0x272727
      text_font: icons35
      text_align: CENTER
    - id: info_or_button_tile_info
      height: SIZE_CONTENT
      pad_all: 0
      pad_top: 6
      bg_opa: TRANSP
      text_color: 0xeebf41
    - id: info_or_button_tile_subtitle
      pad_all: 0
      text_color: 0xababab
      text_font: libreFranklin14
      text_align: CENTER
