substitutions:
  screen_width: 480
  screen_height: 480

packages:
  lvgl: !include ../common/lvgl.yaml
  fonts: !include ../common/fonts.yaml

lvgl:
  style_definitions:
    - id: full_width
      x: 0
      width: ${screen_width}
    - id: full_height
      y: 0
      height: ${screen_height}
    - id: bottom_pager_y
      y: 450
    - id: bottom_tap_area_y
      y: 435
    - id: bottom_tap_area_widget_size
      height: 45
      width: 235
    - id: top_tap_area_y
      y: 0
      height: 70
    - id: leftright_tap_area
      y: 70
      width: 20
      height: 350
    - id: right_tap_area_x
      x: 460
    - id: content_container
      x: 0
      y: 90
      width: ${screen_width}
      height: 342
      pad_all: 0
      pad_left: 18
      bg_opa: TRANSP
    - id: left_central_tap_area 
      x: 20
      y: 20
      width: !lambda return ${screen_width}/2 - 20;
      height: !lambda return ${screen_height} - 2*20;
    - id: right_central_tap_area 
      x: !lambda return ${screen_width}/2;
      y: 20
      width: !lambda return ${screen_width}/2 - 20;
      height: !lambda return ${screen_height} - 2*20;
    - id: page_title_y
      y: 50
    
    # Settings page
    - id: back_button
      x: 6
      height: 40
    - id: settings_item
      width: 443
      radius: 15
      height: 80
    - id: settings_display_brightness_height
      height: 130
    - id: settings_display_brightness_slider
      height: 25
    - id: settings_dropdown
      height: 40
      width: 110
    - id: settings_item_internal_width
      width: 440

    # Floorplan 
    - id: floorplan_pill
      bg_color: 0x000000
      bg_opa: 20%
      radius: 8
      pad_all: 2
      pad_left: 3
      pad_right: 3
      border_width: 0
      width: SIZE_CONTENT
      height: SIZE_CONTENT

    - id: floorplan_pill_large
      bg_color: 0x000000
      bg_opa: 20%
      radius: 10
      pad_all: 3
      pad_left: 5
      pad_right: 5
      border_width: 0
      width: SIZE_CONTENT
      height: SIZE_CONTENT

    - id: floorplan_icon
      text_color: 0xffffff
      text_font: icons18

    - id: floorplan_icon_large
      text_color: 0xffffff
      text_font: icons35

    - id: floorplan_value
      text_color: 0xffffff
      text_font: libreFranklin14

    - id: floorplan_value_large
      text_color: 0xffffff
      text_font: libreFranklin18
 
    # Info tiles
    - id: info_or_button_tile
      width: 216
      height: 165
      radius: 15
      bg_color: 0x272727
      bg_opa: COVER
      pad_all: 0
    - id: info_or_button_tile_small
      width: 140
      height: 107
      radius: 15
      bg_color: 0x272727
      bg_opa: COVER
      pad_all: 0
    - id: info_or_button_tile_wide
      width: 443
      height: 165
      radius: 15
      bg_color: 0x272727
      bg_opa: COVER
      pad_all: 0
    - id: info_or_button_tile_icon
      pad_all: 0
      text_color: 0x272727
      text_font: icons35
      text_align: CENTER
    - id: info_or_button_tile_info
      height: SIZE_CONTENT
      pad_all: 0
      pad_top: 12
      bg_opa: TRANSP
      text_color: 0xeebf41
    - id: info_or_button_tile_subtitle
      pad_all: 0
      text_color: 0xababab
      text_font: libreFranklin14
      text_align: CENTER
