# Hardware definitions for M5Stack Tab5
# NB: This is for "V2" hardware (released after Oct 17 2025)
# with ST7123 display. Display is defined in "landscape" mode.
packages:
  wifi_signal: !include common/wifi_signal_sensor.yaml

esphome:
  platformio_options:
    build_flags:
      # Signals to use little endian encoding for LVGL images
      - -DUSE_RGB565LE

esp32:
  board: esp32-p4-evboard
  flash_size: 16MB
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

esp32_hosted:
  variant: esp32c6
  active_high: true
  clk_pin: GPIO12
  cmd_pin: GPIO13
  d0_pin: GPIO11
  d1_pin: GPIO10
  d2_pin: GPIO9
  d3_pin: GPIO8
  reset_pin: GPIO15
  slot: 1

psram:
  mode: hex
  speed: 200MHz

# See https://community.home-assistant.io/t/m5stack-tab5/888543/23
external_components:
  - source: github://pr#12075
    components: [st7123]
    refresh: 1h
  - source: github://pr#12074
    components: [mipi_dsi]
    refresh: 1h

ota:
  - platform: esphome
    password: ${ota_key}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  on_disconnect:
      - lvgl.label.update:
          id: lvgl_wifi_signal_icon
          text: "\U000F092E"

logger:
  hardware_uart: USB_SERIAL_JTAG


output:
  - platform: ledc
    pin: GPIO22
    id: backlight_pwm
    frequency: 1000Hz

i2c:
  - id: bus_a
    sda: GPIO31
    scl: GPIO32
    frequency: 400kHz
    scan: false

pi4ioe5v6408:
  - id: pi4ioe1
    address: 0x43
    # 0: O - wifi_antenna_int_ext
    # 1: O - speaker_enable
    # 2: O - external_5v_power
    # 3: NC
    # 4: O - lcd reset
    # 5: O - touch panel reset
    # 6: O - camera reset
    # 7: I - headphone detect
  - id: pi4ioe2
    address: 0x44
    # 0: O - wifi_power
    # 1: NC
    # 2: NC
    # 3: O - usb_5v_power
    # 4: O - poweroff pulse
    # 5: O - quick charge enable (inverted)
    # 6: I - charging status
    # 7: O - charge enable

switch:
  - platform: gpio
    id: wifi_power
    name: "WiFi Power"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 0
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: usb_5v_power
    name: "USB Power"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 3
  - platform: gpio
    id: quick_charge
    name: "Quick Charge"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 5
      inverted: true
  - platform: gpio
    id: charge_enable
    name: "Charge Enable"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 7

  - platform: gpio
    id: wifi_antenna_int_ext
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 0
  - platform: gpio
    id: speaker_enable
    name: "Speaker Enable"
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 1
    restore_mode: ALWAYS_ON
  - platform: gpio
    id: external_5v_power
    name: "External 5V Power"
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 2

binary_sensor:
  - platform: gpio
    id: charging
    name: "Charging Status"
    pin:
      pi4ioe5v6408: pi4ioe2
      number: 6
      mode: INPUT_PULLDOWN

  - platform: gpio
    id: headphone_detect
    name: "Headphone Detect"
    pin:
      pi4ioe5v6408: pi4ioe1
      number: 7

sensor:
  - platform: ina226
    address: 0x41
    adc_averaging: 16
    max_current: 8.192A
    shunt_resistance: 0.005ohm
    bus_voltage:
      id: battery_voltage
      name: "Battery Voltage"
    current:
      id: battery_current
      name: "Battery Current"
      # Positive means discharging
      # Negative means charging

    # Tab5 built-in battery discharges from full (8.23 V) to shutdown threshold (6.0 V)
  - platform: template
    name: "Battery Percentage"
    lambda: |-
      float voltage = id(battery_voltage).state;
      // Adjust these values based on your battery's actual min/max voltage
      float min_voltage = 6.0;  // Discharged voltage
      float max_voltage = 8.23;  // Fully charged voltage
      float percentage = (voltage - min_voltage) / (max_voltage - min_voltage) * 100.0;
      if (percentage > 100.0) return 100.0;
      if (percentage < 0.0) return 0.0;
      return percentage;
    update_interval: 60s
    unit_of_measurement: "%"
    accuracy_decimals: 1

touchscreen:
  - platform: st7123
    id: touch
    i2c_id: bus_a
    interrupt_pin: GPIO23
    display: lcd
    update_interval: never
    reset_pin:
      pi4ioe5v6408: pi4ioe1
      number: 5      
    # NB: Those min/max values are *after* swapping (raw x is 0..720).
    calibration:
      x_min: 0
      x_max: 1280
      y_min: 0
      y_max: 720
    # Landscape orientation
    transform:
      swap_xy: true
      mirror_x: true
      mirror_y: false
    on_release:
      - script.execute: activity_detected
    # Calibration debugging:
    # on_touch:
    #   - lambda: |-
    #         ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
    #             touch.x,
    #             touch.y,
    #             touch.x_raw,
    #             touch.y_raw
    #             );

esp_ldo:
  - voltage: 2.5V
    channel: 3

display:
  - platform: mipi_dsi
    id: lcd
    # Landscape orientation
    rotation: 270
    dimensions:
      height: 1280
      width: 720
    model: M5STACK-TAB5-V2
    reset_pin:
      pi4ioe5v6408: pi4ioe1
      number: 4

lvgl:
  byte_order: little_endian 

# The DAC Output select needs to be manually (or with an automation) changed to `LINE1` for the onboard speaker
select:
  - platform: es8388
    dac_output:
      name: DAC Output
    adc_input_mic:
      name: ADC Input Mic
      
  - platform: template
    id: wifi_antenna_select
    name: "WiFi Antenna"
    options:
      - "Internal"
      - "External"
    optimistic: true
    on_value:
      - if:
          condition:
            lambda: return i == 0;
          then:
            - switch.turn_off: wifi_antenna_int_ext
          else:
            - switch.turn_on: wifi_antenna_int_ext

i2s_audio:
  - id: mic_bus
    i2s_lrclk_pin: GPIO29
    i2s_bclk_pin: GPIO27
    i2s_mclk_pin: GPIO30

audio_adc:
  - platform: es7210
    id: es7210_adc
    bits_per_sample: 16bit
    sample_rate: 16000

microphone:
  - platform: i2s_audio
    id: tab5_microphone
    i2s_din_pin: GPIO28
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external

audio_dac:
  - platform: es8388
    id: es8388_dac

speaker:
  - platform: i2s_audio
    id: tab5_speaker
    i2s_dout_pin: GPIO26
    audio_dac: es8388_dac
    dac_type: external
    channel: mono
    buffer_duration: 100ms
    bits_per_sample: 16bit
    sample_rate: 48000

image:
  defaults:
    type: rgb565
    byte_order: little_endian
