substitutions:
  homedicator_package_dir: "HomeDicator-ESPHome-Package"
  api_key: "API key"

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  project:
    name: paulvincentroll.HomeDicator
    version: konstantint edition

  # Only needed for the thermostat widget.
  # includes:
  #  - ${homedicator_package_dir}/HomeDicator/ui/templates/tiles/thermostat/helpers/adjust_color.h

  platformio_options:
    build_unflags: -Werror=all

logger:
  level: INFO

api:
  encryption:
    key: ${api_key}

packages:
  ui: !include ui/ui.yaml
