substitutions:
  homedicator_package_dir: "HomeDicator-ESPHome-Package"
  api_key: "API key"

ota:
  - platform: esphome
    password: ${ota_key}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  on_disconnect:
      - lvgl.label.update:
          id: lvgl_wifi_signal_icon
          text: "\U000F092E"

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  project:
    name: paulvincentroll.HomeDicator
    version: konstantint edition

  # Only needed for the thermostat widget.
  # includes:
  #  - ${homedicator_package_dir}/HomeDicator/ui/templates/tiles/thermostat/helpers/adjust_color.h

  platformio_options:
    build_unflags: -Werror=all

logger:
  level: INFO

api:
  encryption:
    key: ${api_key}

packages:
  # Include all UI components in the right order
  i18n: !include ui/i18n.yaml
  gradients: !include ui/gradients.yaml
  navigation: !include ui/navigation.yaml
  pager_dots: !include ui/bottom_pager_dots.yaml
  settings_page: !include ui/settings_page.yaml
  time: !include ui/time.yaml
  backlight: !include ui/backlight.yaml
  auto_page_cycling: !include ui/auto_page_cycling.yaml
  user_interface_debug_mode: !include ui/user_interface_debug_mode.yaml
  connecting_view: !include ui/connecting_view.yaml
  title_bar: !include ui/title_bar.yaml