substitutions:
  total_pages: 5  # Number of pager dots

esphome:
  on_boot:
    - priority: 800.0
      then:
        - script.execute: create_pager_dots

globals:
  - id: pager_dots
    type: lv_obj_t*[${total_pages}]
    restore_value: no

script:
  - id: create_pager_dots
    then:
      - lambda: |-
          for (int i = 0; i < ${total_pages}; i++) {
            auto dot = lv_obj_create(id(bottom_pager));  // Create each dot object
            lv_obj_set_size(dot, 8, 8);  // Set width and height of the dot (8x8)
            lv_obj_set_style_radius(dot, 4, LV_PART_MAIN);  // Set radius to make it circular
            lv_obj_set_style_bg_color(dot, (i == 0) ? lv_color_hex(0xffffff) : lv_color_hex(0x626262), LV_PART_MAIN);  // Set color based on active/inactive
            lv_obj_set_style_bg_opa(dot, LV_OPA_COVER, LV_PART_MAIN);  // Ensure the background is fully opaque
            lv_obj_set_style_border_width(dot, 0, LV_PART_MAIN);  // Disable borders
            lv_obj_set_style_border_color(dot, lv_color_hex(0x000000), LV_PART_MAIN);  // Set border color to black (doesn't matter since width is 0)
            id(pager_dots)[i] = dot;  // Store the dot reference
          }

  - id: update_pager_dots
    then:
      - lambda: |-
          for (int i = 0; i < ${total_pages}; i++) {
            lv_obj_t* dot = id(pager_dots)[i];
            lv_obj_set_style_bg_color(dot, (i == id(current_page)) ? lv_color_hex(0xffffff) : lv_color_hex(0x626262), LV_PART_MAIN);  // Active color is white, inactive is gray
          }

lvgl:
  top_layer:
    widgets:
      - obj:
          id: bottom_pager
          styles: ["full_width", "bottom_pager_y"]
          pad_all: 0
          height: SIZE_CONTENT
          bg_opa: TRANSP
          layout:
            type: FLEX
            flex_flow: ROW
            flex_align_main: CENTER
            flex_align_cross: CENTER
          widgets: []
