substitutions:
  first_page_id: settings  # Replace this with actual first page.
  page_transition_time: 150ms # How long to animate the transition between pages.

globals:
  - id: current_page
    type: int
    restore_value: no
    initial_value: "0"
  - id: page_controls_hidden
    type: bool
    initial_value: "false"
    restore_value: no

lvgl:
  top_layer:
    widgets:
      - obj:
          id: top_tap_area
          styles: ["top_tap_area_y", "full_width"]
          pad_all: 0
          bg_opa: TRANSP
          on_press:
            then:
              - script.execute: hide_page_control_elements
              - lvgl.page.show:
                  animation: OVER_BOTTOM
                  time: ${page_transition_time}
                  id: settings
      - obj:
          id: bottom_tap_area
          styles: ["full_width", "bottom_tap_area_y"]
          pad_all: 0
          height: SIZE_CONTENT
          bg_opa: TRANSP
          layout:
            type: FLEX
            flex_flow: ROW
            flex_align_main: SPACE_BETWEEN
            flex_align_cross: CENTER
          widgets:
            - obj:
                bg_opa: TRANSP
                styles: bottom_tap_area_widget_size
                on_press:
                  then:
                    - script.execute: previous_page
            - obj:
                bg_opa: TRANSP
                styles: bottom_tap_area_widget_size
                on_press:
                  then:
                    - script.execute: next_page
      - obj:
          id: left_tap_area
          x: 0
          styles: leftright_tap_area
          bg_opa: TRANSP
          pad_all: 0
          on_press:
            then:
              - script.execute: previous_page
      - obj:
          id: right_tap_area
          styles: ["leftright_tap_area", "right_tap_area_x"]
          bg_opa: TRANSP
          pad_all: 0
          on_press:
            then:
              - script.execute: next_page

script:
  - id: hide_page_control_elements
    then:
      - lvgl.widget.hide: top_tap_area
      - lvgl.widget.hide: bottom_tap_area
      - lvgl.widget.hide: left_tap_area
      - lvgl.widget.hide: right_tap_area
      - lvgl.widget.hide: bottom_pager
      - globals.set:
          id: page_controls_hidden
          value: 'true'


  - id: show_page_control_elements
    then:
      - lvgl.widget.show: top_tap_area
      - lvgl.widget.show: bottom_tap_area
      - lvgl.widget.show: left_tap_area
      - lvgl.widget.show: right_tap_area
      - lvgl.widget.show: bottom_pager
      - globals.set:
          id: page_controls_hidden
          value: 'false'
  
  - id: go_to_first_page
    then:
      - globals.set:
          id: current_page
          value: '0'
      - lvgl.page.show:
          id: ${first_page_id}
          animation: MOVE_LEFT
      - script.execute: update_pager_dots
 
  - id: next_page
    then:
      - globals.set:
          id: current_page
          value: !lambda |-
            int next_page = id(current_page) + 1;
            return (next_page >= ${total_pages}) ? 0 : next_page;  // Loop back to 0 if exceeding the total pages
      - lvgl.page.next:
          animation: MOVE_LEFT
          time: ${page_transition_time}
      - script.execute: update_pager_dots

  - id: previous_page
    then:
      - globals.set:
          id: current_page
          value: !lambda |-
            int prev_page = id(current_page) - 1;
            return (prev_page < 0) ? ${total_pages} - 1 : prev_page;  // Loop back to max page if going below 0
      - lvgl.page.previous:
          animation: MOVE_RIGHT
          time: ${page_transition_time}
      - script.execute: update_pager_dots
